"""empty message

Revision ID: 020145664ae9
Revises: None
Create Date: 2016-02-20 19:37:02.496022

"""

# revision identifiers, used by Alembic.
revision = '020145664ae9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productimageparsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xpath', sa.String(), nullable=True),
    sa.Column('elementTag', sa.String(), nullable=True),
    sa.Column('tagAttribute', sa.String(), nullable=True),
    sa.Column('attributeValue', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productnameparsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xpath', sa.String(), nullable=True),
    sa.Column('elementTag', sa.String(), nullable=True),
    sa.Column('tagAttribute', sa.String(), nullable=True),
    sa.Column('attributeValue', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productpriceparsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xpath', sa.String(), nullable=True),
    sa.Column('elementTag', sa.String(), nullable=True),
    sa.Column('tagAttribute', sa.String(), nullable=True),
    sa.Column('attributeValue', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productpriceparsers')
    op.drop_table('productnameparsers')
    op.drop_table('productimageparsers')
    op.drop_table('products')
    op.drop_table('merchants')
    ### end Alembic commands ###
