"""empty message

Revision ID: 1e2fab453bc5
Revises: 9523e4bc26b8
Create Date: 2016-02-27 21:46:10.001879

"""

# revision identifiers, used by Alembic.
revision = '1e2fab453bc5'
down_revision = '9523e4bc26b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('targetPrice', sa.Float(), nullable=True),
    sa.Column('currentPrice', sa.Float(), nullable=True),
    sa.Column('tweetAt', sa.String(), nullable=True),
    sa.Column('reachedTarget', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentPrice', sa.Float(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerthistory')
    op.drop_table('alerts')
    ### end Alembic commands ###
