"""empty message

Revision ID: ef3f3ea52d84
Revises: 1e2fab453bc5
Create Date: 2016-02-28 13:14:38.331948

"""

# revision identifiers, used by Alembic.
revision = 'ef3f3ea52d84'
down_revision = '1e2fab453bc5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currentPrice', sa.Float(), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricehistory')
    ### end Alembic commands ###
